spring:
  application:
    name: sleeping-ai-nocode
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sleeping_ai_nocode
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  session:
    timeout: 86400

cors:
  allowed-origins: http://localhost:*,http://127.0.0.1:*

server:
  port: 8123
  servlet:
    context-path: /api

mybatis-flex:
  configuration:
    map-underscore-to-camel-case: true

sa-token:
  token-name: satoken
  timeout: 86400
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false

springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.sleeping.ainocode.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
